# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='calc_rate_request',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=14),
        ),
    ]
